stages:
  - build
  - test
  - deploy
  - cleanup

default:
  retry:
    max: 2
    when:
      - unknown_failure
      - api_failure
      - stuck_or_timeout_failure
      - runner_system_failure
      - runner_unsupported
      - stale_schedule
      - job_execution_timeout
      - unmet_prerequisites
      - scheduler_failure
      - data_integrity_failure
variables:
  TAG_NAME: ${CI_COMMIT_REF_SLUG}
  IMAGE_NAME: ${CI_REGISTRY_IMAGE}/back
  IMAGE_WITH_TAG: ${IMAGE_NAME}:${TAG_NAME}
  DEPLOYMENT_PATH: /tcm_deployment/${CI_PROJECT_NAME}

include:
  - local: .gitlab/gitlab-ci-merge-request.yml
  - local: .gitlab/gitlab-ci-branch-main.yml